stages:
- build

linux:
    stage: build
    script:
        - apt-get update
        - apt-get install --no-install-recommends xz-utils curl git ca-certificates curl -y
        - curl -s https://packagecloud.io/install/repositories/anarchytools/AT/script.deb.sh | bash
        - apt-get install atbuild package-deb -y
        - git submodule update --recursive --init
        - atbuild check
        - atbuild package --use-overlay static
    tags:
        - autoscale-linux
    image: drewcrawford/swift:latest
    artifacts:
        paths:
            - bin/atpm-*.tar.xz
            - bin/*.deb

osx:
    stage: build
    script:
        - git submodule update --recursive --init
        - atbuild check
        - atbuild package --use-overlay static
    tags:
        - openswift
        - atbuild
    artifacts:
        paths:
            - bin/atpm-*.tar.xz
            - bin/atpm.rb
