stages:
- build

linux:
    stage: build
    script:
        - apt-get update
        - apt-get install --no-install-recommends xz-utils atbuild package-deb curl -y
        - git submodule update --recursive --init
        - atbuild check
        - atbuild package --use-overlay static --configuration release
    tags:
        - autoscale-linux
    image: drewcrawford/buildbase:latest
    artifacts:
        paths:
            - bin/atpm-*.tar.xz
            - bin/*.deb

osx:
    stage: build
    script:
        - git submodule update --recursive --init
        - atbuild check
        - atbuild package --use-overlay static --configuration release
    tags:
        - openswift
        - atbuild
    artifacts:
        paths:
            - bin/atpm-*.tar.xz
            - bin/atpm.rb
